apiVersion: castai.upbound.io/v1alpha1
kind: NodeConfigurationDefault
metadata:
  annotations:
    meta.upbound.io/example-id: castai/v1alpha1/nodeconfigurationdefault
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    configurationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
